<x-layouts.app title="Vendors" wide :breadcrumbs="[['label'=>'Overview','url'=>route('home')],['label'=>'Vendors']]">
    <x-ui.page-header title="Vendors" subtitle="Reusable supplier records independent from login accounts."><x-slot:actions>@can('create',App\Models\Vendor::class)<a class="btn btn-primary" href="{{ route('vendors.create') }}">Create vendor</a>@endcan</x-slot:actions></x-ui.page-header>
    <x-ui.filter-bar :action="route('vendors.index')" :clear-url="route('vendors.index')">
        <div class="col-12 col-xl-4"><label class="form-label" for="q">Search</label><input class="form-control" id="q" name="q" value="{{ $filters['q']??'' }}" placeholder="Name, email, phone, or contact"></div>
        <div class="col-6 col-xl-2"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">Active</option><option value="archived" @selected(($filters['status']??'')==='archived')>Archived</option></select></div>
        <div class="col-6 col-xl-3"><label class="form-label" for="category">Category</label><select class="form-select" id="category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)($filters['category']??'')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div>
        @if($branches->isNotEmpty())<div class="col-6 col-xl-3"><label class="form-label" for="branch">Branch</label><select class="form-select" id="branch" name="branch"><option value="">All branches</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)($filters['branch']??'')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>@endif
    </x-ui.filter-bar>
    <x-ui.data-table :columns="[['label'=>'Vendor'],['label'=>'Categories'],['label'=>'Contact'],['label'=>'Status'],['label'=>'Action']]" caption="Vendor records" :empty="$vendors->isEmpty()" empty-title="No vendors match these filters">
        @foreach($vendors as $vendor)<tr><td><a class="fw-semibold text-decoration-none" href="{{ route('vendors.show',$vendor) }}">{{ $vendor->display_name }}</a>@if($vendor->user)<span class="d-block small text-secondary">Portal: {{ $vendor->user->email }}</span>@endif</td><td>{{ $vendor->categories->pluck('name')->join(', ') ?: '—' }}</td><td>{{ $vendor->primary_email ?: '—' }}<span class="d-block small text-secondary">{{ $vendor->primary_phone ?: '—' }}</span></td><td><x-ui.status-badge :status="$vendor->status"/></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('vendors.show',$vendor) }}">View</a></td></tr>@endforeach
    </x-ui.data-table><x-ui.pagination :paginator="$vendors"/>
</x-layouts.app>
