<x-layouts.app :title="$vendor->display_name" wide :breadcrumbs="[['label'=>'Vendors','url'=>route('vendors.index')],['label'=>$vendor->display_name]]">
    <x-ui.page-header :title="$vendor->display_name" :subtitle="ucfirst($vendor->status).' vendor'">
        <x-slot:actions>@can('update',$vendor)<a class="btn btn-outline-primary" href="{{ route('vendors.edit',$vendor) }}">Edit vendor</a>@endcan</x-slot:actions>
    </x-ui.page-header>
    <div class="row g-4"><div class="col-xl-8">
        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Vendor details</h2><dl class="row mb-0">
            <dt class="col-sm-4">Categories</dt><dd class="col-sm-8">{{ $vendor->categories->pluck('name')->join(', ')?:'—' }}</dd>
            <dt class="col-sm-4">Contact</dt><dd class="col-sm-8">{{ $vendor->primary_email?:'—' }} · {{ $vendor->primary_phone?:'—' }}</dd>
            <dt class="col-sm-4">Service branch</dt><dd class="col-sm-8">{{ $vendor->branch?->name??'Unscoped' }}</dd>
            <dt class="col-sm-4">Portal link</dt><dd class="col-sm-8">{{ $vendor->user?->email??'Not linked' }}</dd>
            <dt class="col-sm-4">Conflict policy</dt><dd class="col-sm-8">{{ str($vendor->availability_conflict_policy)->headline() }} on overlapping commitments</dd>
            <dt class="col-sm-4">Rating summary</dt><dd class="col-sm-8">{{ $vendor->ratings->isNotEmpty() ? number_format((float)$vendor->ratings->avg('score'),1).' / 5' : 'Not rated' }}</dd>
            <dt class="col-sm-4">Notes</dt><dd class="col-sm-8">{{ $vendor->notes?:'—' }}</dd>
        </dl></div></section>
        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Contacts</h2>
            <x-ui.data-table :columns="[['label'=>'Name'],['label'=>'Details'],['label'=>'Action']]" caption="Vendor contacts" :empty="$vendor->contacts->isEmpty()" empty-title="No contacts">
                @foreach($vendor->contacts as $contact)<tr><td>{{ $contact->name }} @if($contact->is_primary)<span class="badge text-bg-primary">Primary</span>@endif</td><td>{{ $contact->email?:'—' }}<span class="d-block small text-secondary">{{ $contact->phone?:'—' }}</span></td><td>@can('update',$vendor)<form method="POST" action="{{ route('vendors.contacts.destroy',[$vendor,$contact]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Archive</button></form>@endcan</td></tr>@endforeach
            </x-ui.data-table>
            @can('update',$vendor)<hr><form method="POST" action="{{ route('vendors.contacts.store',$vendor) }}">@csrf<div class="row"><div class="col-md-4"><x-ui.form.input name="name" label="Contact name" required/></div><div class="col-md-4"><x-ui.form.input name="email" label="Email" type="email"/></div><div class="col-md-4"><x-ui.form.input name="phone" label="Phone"/></div></div><input type="hidden" name="is_primary" value="0"><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_primary" value="1" id="vendor-contact-primary"><label class="form-check-label" for="vendor-contact-primary">Primary contact</label></div><button class="btn btn-primary">Add contact</button></form>@endcan
        </div></section>
        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Service areas</h2><ul class="list-group mb-3">@forelse($vendor->serviceAreas as $area)<li class="list-group-item d-flex justify-content-between">{{ $area->name }} @can('update',$vendor)<form method="POST" action="{{ route('vendors.service-areas.destroy',[$vendor,$area]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Archive</button></form>@endcan</li>@empty<li class="list-group-item text-secondary">No service areas recorded.</li>@endforelse</ul>@can('update',$vendor)<form method="POST" action="{{ route('vendors.service-areas.store',$vendor) }}">@csrf<div class="input-group"><input class="form-control" name="name" aria-label="Service area" placeholder="City, region, or coverage area" required><button class="btn btn-primary">Add</button></div></form>@endcan</div></section>
        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Documents</h2><p class="text-secondary">Files use authorized private download routes.</p>@forelse($vendor->documentLinks as $link)<a class="d-block" href="{{ route('documents.show',$link->document) }}">{{ $link->document->title }}</a>@empty<span class="text-secondary">No linked documents.</span>@endforelse</div></section>
        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Availability</h2>
            <x-ui.data-table :columns="[['label'=>'Window'],['label'=>'Rule'],['label'=>'Notes'],['label'=>'Action']]" caption="Vendor availability rules" :empty="$vendor->availabilities->isEmpty()" empty-title="No availability rules">
                @foreach($vendor->availabilities as $rule)<tr><td>{{ $rule->starts_at->format('Y-m-d H:i') }} – {{ $rule->ends_at->format('Y-m-d H:i') }}</td><td>{{ str($rule->status)->headline() }} · {{ str($rule->conflict_action)->headline() }}</td><td>{{ $rule->notes?:'—' }}</td><td>@can('vendors.manage-availability')<form method="POST" action="{{ route('vendors.availability.destroy',[$vendor,$rule]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Archive</button></form>@endcan</td></tr>@endforeach
            </x-ui.data-table>
            @can('vendors.manage-availability')<hr><form method="POST" action="{{ route('vendors.availability.store',$vendor) }}">@csrf<div class="row g-3"><div class="col-md-6"><x-ui.form.input name="starts_at_local" label="Starts" type="datetime-local" required/></div><div class="col-md-6"><x-ui.form.input name="ends_at_local" label="Ends" type="datetime-local" required/></div><div class="col-md-4"><x-ui.form.select name="status" label="Rule" :options="collect(['available'=>'Available','unavailable'=>'Unavailable'])" value="unavailable" required/></div><div class="col-md-4"><x-ui.form.select name="conflict_action" label="On conflict" :options="collect(['warn'=>'Warn','block'=>'Block'])" value="warn" required/></div><div class="col-md-4"><x-ui.form.input name="notes" label="Notes"/></div></div><button class="btn btn-primary">Add rule</button></form>@endcan
        </div></section>
        <section class="card"><div class="card-body p-4"><h2 class="h4">Event assignments</h2>
            <x-ui.data-table :columns="[['label'=>'Event'],['label'=>'Service'],['label'=>'Status'],['label'=>'Action']]" caption="Vendor event history" :empty="$vendor->assignments->isEmpty()" empty-title="No event assignments">
                @foreach($vendor->assignments as $assignment)<tr><td>{{ $assignment->event->reference_number }} · {{ $assignment->event->name }}</td><td>{{ $assignment->category->name }}</td><td><x-ui.status-badge :status="$assignment->status"/></td><td>@can('view',$assignment)<a class="btn btn-sm btn-outline-primary" href="{{ route('events.vendors.show',[$assignment->event,$assignment]) }}">Open</a>@endcan</td></tr>@endforeach
            </x-ui.data-table>
        </div></section>
    </div><aside class="col-xl-4">
        @can('assignUser',$vendor)<section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Portal account</h2><p class="text-secondary">Linking is optional and never automatic.</p><form method="POST" action="{{ route('vendors.user-link',$vendor) }}">@csrf @method('PUT')<x-ui.form.select name="user_id" label="Vendor-role user" :options="$users->pluck('email','id')" :value="$vendor->user_id" placeholder="No linked user"/><button class="btn btn-outline-primary">Update link</button></form></div></section>@endcan
        @if($vendor->status==='active')@can('archive',$vendor)<section class="card"><div class="card-body p-4"><h2 class="h4">Archive vendor</h2><form method="POST" action="{{ route('vendors.status',$vendor) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="archive"><x-ui.form.textarea name="reason" label="Reason" required/><button class="btn btn-warning">Archive</button></form></div></section>@endcan @else @can('reactivate',$vendor)<form method="POST" action="{{ route('vendors.status',$vendor) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="reactivate"><button class="btn btn-success">Reactivate vendor</button></form>@endcan @endif
    </aside></div>
</x-layouts.app>
