<x-layouts.app :title="$eventTemplate->name" wide :breadcrumbs="[['label'=>'Settings','url'=>route('settings.edit')],['label'=>'Event templates','url'=>route('settings.event-templates.index')],['label'=>$eventTemplate->name]]">
<x-ui.page-header :title="$eventTemplate->name" :subtitle="($eventTemplate->category?->name??'Uncategorized').' · '.ucfirst($eventTemplate->status)"><x-slot:actions>@can('update',$eventTemplate)<a class="btn btn-outline-primary" href="{{ route('settings.event-templates.edit',$eventTemplate) }}">Edit</a>@endcan @can('duplicate',$eventTemplate)<form class="d-inline" method="POST" action="{{ route('settings.event-templates.duplicate',$eventTemplate) }}">@csrf<button class="btn btn-primary">Duplicate</button></form>@endcan</x-slot:actions></x-ui.page-header>
<div class="row g-4"><div class="col-xl-8">
<section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Template guidance</h2><p>{{ $eventTemplate->description?:'No description.' }}</p><h3 class="h5">Service notes</h3><p class="mb-0">{{ $eventTemplate->service_notes?:'No service notes.' }}</p>@if($eventTemplate->sourceTemplate)<p class="small text-secondary mt-3 mb-0">Duplicated from {{ $eventTemplate->sourceTemplate->name }}.</p>@endif</div></section>
<section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Suggested modules</h2><div class="row g-3"><div class="col-md-6"><h3 class="h6">Default enabled</h3><ul>@forelse($eventTemplate->modules->where('recommendation','default') as $module)<li>{{ $module->definition?->label??$module->module_key }} <code>{{ $module->module_key }}</code></li>@empty<li class="text-secondary">None. All specialized modules may remain disabled.</li>@endforelse</ul></div><div class="col-md-6"><h3 class="h6">Optional add-ons</h3><ul>@forelse($eventTemplate->modules->where('recommendation','optional') as $module)<li>{{ $module->definition?->label??$module->module_key }} <code>{{ $module->module_key }}</code></li>@empty<li class="text-secondary">None.</li>@endforelse</ul></div></div>@foreach($warnings as $warning)<div class="alert alert-warning mb-2" role="status">Suggestion only: {{ $warning }}</div>@endforeach</div></section>
<div class="row g-4"><div class="col-md-6"><section class="card h-100"><div class="card-body p-4"><h2 class="h4">Starter tasks</h2><ul>@forelse($eventTemplate->starter_tasks??[] as $task)<li>{{ $task['title'] }}</li>@empty<li class="text-secondary">No starter tasks.</li>@endforelse</ul></div></section></div><div class="col-md-6"><section class="card h-100"><div class="card-body p-4"><h2 class="h4">Budget lines</h2><ul>@forelse($eventTemplate->budget_lines??[] as $line)<li>{{ ucfirst($line['direction']) }} · {{ $line['label'] }} @if(filled($line['amount']))· {{ $line['amount'] }}@endif</li>@empty<li class="text-secondary">No starter budget lines.</li>@endforelse</ul></div></section></div></div>
</div><aside class="col-xl-4">
<section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Snapshot rule</h2><p class="mb-0">Applying this template later will copy module states, tasks, notes, and budget suggestions. Editing this template never rewrites an existing Event.</p></div></section>
@if($eventTemplate->status==='active')@can('archive',$eventTemplate)<section class="card"><div class="card-body p-4"><h2 class="h4">Archive template</h2><form method="POST" action="{{ route('settings.event-templates.status',$eventTemplate) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="archive"><x-ui.form.textarea name="reason" label="Reason" required/><button class="btn btn-warning">Archive</button></form></div></section>@endcan @else @can('reactivate',$eventTemplate)<form method="POST" action="{{ route('settings.event-templates.status',$eventTemplate) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="reactivate"><button class="btn btn-success">Reactivate template</button></form>@endcan @endif
</aside></div></x-layouts.app>
