<x-layouts.app :title="$registrationForm->exists ? 'Registration form builder' : 'Create registration form'" :breadcrumbs="[['label'=>'Events','url'=>route('events.index')],['label'=>$event->name,'url'=>route('events.show',$event)],['label'=>'Registration forms','url'=>route('events.registration-forms.index',$event)],['label'=>$registrationForm->exists?'Builder':'Create']]">
    <x-ui.page-header :title="$registrationForm->exists ? 'Registration form builder' : 'Create registration form'" subtitle="Only allow-listed field types and validation constraints are supported."/>
    <form method="POST" action="{{ $registrationForm->exists ? route('events.registration-forms.update',[$event,$registrationForm]) : route('events.registration-forms.store',$event) }}" class="card card-body mb-4">
        @csrf @if($registrationForm->exists) @method('PUT') @endif
        <div class="row g-3">
            <div class="col-md-6"><label class="form-label" for="name">Form name</label><input class="form-control" id="name" name="name" required maxlength="191" value="{{ old('name',$registrationForm->name) }}"></div>
            <div class="col-md-3"><label class="form-label" for="duplicate_policy">Duplicate policy</label><select class="form-select" id="duplicate_policy" name="duplicate_policy"><option value="block_email" @selected(old('duplicate_policy',$registrationForm->duplicate_policy ?? 'block_email')==='block_email')>Block same email</option><option value="allow" @selected(old('duplicate_policy',$registrationForm->duplicate_policy)==='allow')>Allow duplicates</option></select></div>
            <div class="col-md-3"><label class="form-label" for="confirmation_channel">Confirmation</label><select class="form-select" id="confirmation_channel" name="confirmation_channel"><option value="none">None</option><option value="email" @selected(old('confirmation_channel',$registrationForm->confirmation_channel)==='email')>Email</option><option value="sms" @selected(old('confirmation_channel',$registrationForm->confirmation_channel)==='sms')>SMS (adapter disabled until configured)</option></select></div>
            <div class="col-12"><label class="form-label" for="privacy_text">Privacy text</label><textarea class="form-control" id="privacy_text" name="privacy_text" rows="3" maxlength="5000">{{ old('privacy_text',$registrationForm->privacy_text) }}</textarea></div>
            <div class="col-12 d-flex gap-4"><div class="form-check"><input type="hidden" name="approval_required" value="0"><input class="form-check-input" type="checkbox" id="approval_required" name="approval_required" value="1" @checked(old('approval_required',$registrationForm->exists ? $registrationForm->approval_required : true))><label class="form-check-label" for="approval_required">Require manager approval</label></div><div class="form-check"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" id="is_active" name="is_active" value="1" @checked(old('is_active',$registrationForm->exists ? $registrationForm->is_active : true))><label class="form-check-label" for="is_active">Active</label></div></div>
        </div>
        <div class="mt-3"><button class="btn btn-primary" type="submit">{{ $registrationForm->exists ? 'Save settings' : 'Create form' }}</button></div>
    </form>

    @if($registrationForm->exists)
        <section class="card card-body mb-4" aria-labelledby="publishing-title"><h2 class="h5" id="publishing-title">Publishing</h2><p class="text-secondary">The public slug is randomized. Unpublishing immediately denies public access without deleting submissions.</p><form method="POST" action="{{ route('events.registration-forms.publish',[$event,$registrationForm]) }}">@csrf @method('PATCH')<input type="hidden" name="publish" value="{{ $registrationForm->published_at ? 0 : 1 }}"><button class="btn {{ $registrationForm->published_at ? 'btn-outline-warning' : 'btn-success' }}" type="submit">{{ $registrationForm->published_at ? 'Unpublish' : 'Publish' }}</button>@if($registrationForm->isPublished()) <a class="ms-2" href="{{ route('public.registrations.show',$registrationForm->public_slug) }}" target="_blank" rel="noopener">Preview public form</a>@endif</form></section>

        <section class="card card-body mb-4" aria-labelledby="fields-title"><h2 class="h5" id="fields-title">Fields</h2>
            @if($registrationForm->fields->isNotEmpty())<form method="POST" action="{{ route('events.registration-fields.reorder',[$event,$registrationForm]) }}" class="mb-4">@csrf @method('PUT')<p class="small text-secondary">Enter each field’s position; smaller values appear first.</p>@foreach($registrationForm->fields as $field)<div class="row g-2 align-items-end border-top py-2"><div class="col"><strong>{{ $field->label }}</strong><span class="d-block small text-secondary">{{ $field->key }} · {{ $field->type }}{{ $field->is_required?' · required':'' }}{{ !$field->is_active?' · inactive':'' }}</span></div><div class="col-auto"><a class="btn btn-sm btn-outline-secondary" href="{{ route('events.registration-fields.edit',[$event,$registrationForm,$field]) }}">Edit</a></div><div class="col-auto"><label class="form-label small" for="order_{{ $field->id }}">Position</label><input class="form-control form-control-sm" style="width:6rem" id="order_{{ $field->id }}" name="positions[{{ $field->id }}]" type="number" value="{{ $field->display_order }}"></div><input type="hidden" name="field_ids[]" value="{{ $field->id }}"></div>@endforeach<button class="btn btn-sm btn-outline-primary mt-2" type="submit">Save field order</button></form>@endif
            <h3 class="h6">Add field</h3><form method="POST" action="{{ route('events.registration-fields.store',[$event,$registrationForm]) }}">@csrf @include('events.registrations.forms._field-form',['field'=>new App\Models\RegistrationField])<button class="btn btn-primary" type="submit">Add field</button></form>
        </section>
    @endif
</x-layouts.app>
