<x-layouts.app :title="$invoice->invoice_number ?? 'Draft Invoice'" :breadcrumbs="[['label' => 'Events', 'url' => route('events.index')], ['label' => $event->reference_number, 'url' => route('events.show', $event)], ['label' => 'Invoices', 'url' => route('events.invoices.index', $event)], ['label' => $invoice->invoice_number ?? 'Draft']]" wide>
    <x-ui.page-header :title="$invoice->invoice_number ?? 'Draft Invoice #'.$invoice->id" :subtitle="$invoice->client_name.' · '.$invoice->currency_code">
        <x-slot:actions>
            @can('update', $invoice)<a class="btn btn-outline-primary" href="{{ route('events.invoices.edit', [$event, $invoice]) }}">Edit Draft</a>@endcan
            @if($invoice->invoice_number && auth()->user()->hasPermission('invoices.export'))<a class="btn btn-outline-secondary" href="{{ route('events.invoices.print', [$event, $invoice]) }}" target="_blank">Print</a><a class="btn btn-outline-secondary" href="{{ route('events.invoices.pdf', [$event, $invoice]) }}">PDF</a>@endif
        </x-slot:actions>
    </x-ui.page-header>
    <div class="row g-4 mb-4"><div class="col-md-8"><div class="card card-body h-100"><div class="d-flex justify-content-between"><div><div class="small text-secondary">Status</div><x-ui.status-badge :status="$invoice->displayStatus()"/></div><div class="text-end"><div class="small text-secondary">Due date</div><strong>{{ $invoice->due_date->format('Y-m-d') }}</strong></div></div><hr><div class="row"><div class="col-md-6"><strong>From</strong><div>{{ $invoice->seller_name ?: config('app.name') }}</div><div class="small text-secondary">{{ $invoice->seller_address }}<br>{{ $invoice->seller_contact }}</div></div><div class="col-md-6"><strong>Bill to</strong><div>{{ $invoice->client_name }}</div><div class="small text-secondary">{{ $invoice->client_address }}<br>{{ $invoice->client_contact }}</div></div></div></div></div><div class="col-md-4"><div class="card card-body h-100"><div class="d-flex justify-content-between"><span>Total</span><strong>{{ $invoice->currency_code }} {{ number_format((float) $invoice->total, 2) }}</strong></div><div class="d-flex justify-content-between"><span>Payments</span><strong>{{ $invoice->currency_code }} {{ number_format((float) $applied, 2) }}</strong></div><hr><div class="d-flex justify-content-between fs-5"><span>Balance</span><strong>{{ $invoice->currency_code }} {{ number_format((float) $balance, 2) }}</strong></div></div></div></div>
    <div class="card shadow-sm mb-4"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Description</th><th class="text-end">Qty</th><th class="text-end">Unit</th><th class="text-end">Discount</th><th class="text-end">Tax</th><th class="text-end">Total</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->description }}</td><td class="text-end">{{ $item->quantity }}</td><td class="text-end">{{ number_format((float) $item->unit_price, 2) }}</td><td class="text-end">{{ number_format((float) $item->discount_amount, 2) }}</td><td class="text-end">{{ number_format((float) $item->tax_amount, 2) }}</td><td class="text-end">{{ number_format((float) $item->line_total, 2) }}</td></tr>@endforeach</tbody><tfoot><tr><th colspan="5" class="text-end">Subtotal</th><th class="text-end">{{ number_format((float) $invoice->subtotal, 2) }}</th></tr><tr><th colspan="5" class="text-end">Discount</th><th class="text-end">-{{ number_format((float) $invoice->discount_total, 2) }}</th></tr><tr><th colspan="5" class="text-end">Tax</th><th class="text-end">{{ number_format((float) $invoice->tax_total, 2) }}</th></tr><tr><th colspan="5" class="text-end">Total</th><th class="text-end">{{ $invoice->currency_code }} {{ number_format((float) $invoice->total, 2) }}</th></tr></tfoot></table></div></div>
    <div class="row g-4">
        <div class="col-lg-6"><div class="card card-body h-100"><h2 class="h5">Actions</h2>@can('issue', $invoice)<form method="POST" action="{{ route('events.invoices.issue', [$event, $invoice]) }}">@csrf<button class="btn btn-primary">Issue immutable Invoice</button></form>@endcan
        @can('email', $invoice)<form class="row g-2 mt-2" method="POST" action="{{ route('events.invoices.email', [$event, $invoice]) }}">@csrf<div class="col"><label class="visually-hidden" for="recipient">Recipient</label><input class="form-control" id="recipient" name="recipient" type="email" required value="{{ $event->client?->primary_email }}" placeholder="client@example.com"></div><div class="col-auto"><button class="btn btn-outline-primary">Email PDF</button></div></form>@endcan
        @can('cancel', $invoice)<form class="mt-3" method="POST" action="{{ route('events.invoices.cancel', [$event, $invoice]) }}">@csrf<label class="form-label" for="cancel_reason">Cancellation reason</label><textarea class="form-control" id="cancel_reason" name="reason" required></textarea><button class="btn btn-outline-danger mt-2">Cancel Invoice</button></form>@endcan
        @can('credit', $invoice)<form class="mt-3" method="POST" action="{{ route('events.invoices.credit', [$event, $invoice]) }}">@csrf<label class="form-label" for="credit_reason">Credit reason</label><textarea class="form-control" id="credit_reason" name="reason" required></textarea><button class="btn btn-outline-danger mt-2">Issue credit note</button></form>@endcan</div></div>
        <div class="col-lg-6"><div class="card card-body h-100"><h2 class="h5">Traceability</h2><ul class="list-group list-group-flush">@foreach($invoice->statusHistory as $history)<li class="list-group-item px-0"><strong>{{ str($history->to_status)->headline() }}</strong><div class="small text-secondary">{{ $history->changed_at }} · {{ $history->actor?->name ?? 'System' }} · {{ $history->reason }}</div></li>@endforeach</ul>@if($invoice->deliveries->isNotEmpty())<h3 class="h6 mt-3">Email attempts</h3>@foreach($invoice->deliveries as $delivery)<div class="small">{{ $delivery->attempted_at }} · {{ $delivery->recipient }} · {{ str($delivery->status)->headline() }}</div>@endforeach@endif</div></div>
    </div>
</x-layouts.app>
