<x-layouts.app title="Staff operations" wide :breadcrumbs="[['label'=>'Staff','url'=>route('staff.index')],['label'=>'Operations']]">
    <x-ui.page-header title="Staff operations" subtitle="Schedules, assignments, leave, attendance, salary tracking, and performance"/>
    <x-ui.filter-bar :action="route('staff.operations.index')">
        <div class="col-md-3"><x-ui.form.input name="q" label="Assignment search" :value="$filters['q']??''"/></div>
        <div class="col-md-3"><x-ui.form.select name="staff" label="Staff" :options="$profiles->pluck('display_name','id')" :value="$filters['staff']??''" placeholder="All accessible staff"/></div>
        <div class="col-md-2"><x-ui.form.input name="from" label="From" type="date" :value="$filters['from']??''"/></div>
        <div class="col-md-2"><x-ui.form.input name="to" label="To" type="date" :value="$filters['to']??''"/></div>
        <div class="col-md-2"><x-ui.form.input name="status" label="Status" :value="$filters['status']??''"/></div>
    </x-ui.filter-bar>

    <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Event assignments</h2>
        <x-ui.data-table :columns="[['label'=>'Staff'],['label'=>'Event'],['label'=>'Role'],['label'=>'Schedule'],['label'=>'Status']]" caption="Staff event assignments" :empty="$assignments->isEmpty()" empty-title="No assignments match">
            @foreach($assignments as $assignment)<tr><td>{{ $assignment->staff->display_name }}</td><td><a href="{{ route('events.show',$assignment->event) }}">{{ $assignment->event->reference_number }}</a></td><td>{{ $assignment->role_title }}</td><td>{{ $assignment->scheduled_starts_at->setTimezone($timezone)->format('Y-m-d H:i') }} – {{ $assignment->scheduled_ends_at->setTimezone($timezone)->format('Y-m-d H:i T') }}</td><td><x-ui.status-badge :status="$assignment->status"/> @if($assignment->conflict_overridden)<span class="badge text-bg-warning">Override</span>@endif</td></tr>@endforeach
        </x-ui.data-table>{{ $assignments->links() }}
    </div></section>

    <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Shifts</h2>
        <x-ui.data-table :columns="[['label'=>'Staff'],['label'=>'Shift'],['label'=>'Window'],['label'=>'Status'],['label'=>'Action']]" caption="Staff shifts" :empty="$shifts->isEmpty()" empty-title="No shifts match">
            @foreach($shifts as $shift)<tr><td>{{ $shift->staff->display_name }}</td><td>{{ $shift->title }}<span class="d-block small text-secondary">{{ $shift->location ?: 'No location' }}</span></td><td>{{ $shift->starts_at->setTimezone($timezone)->format('Y-m-d H:i') }} – {{ $shift->ends_at->setTimezone($timezone)->format('Y-m-d H:i T') }}</td><td><x-ui.status-badge :status="$shift->status"/> @if($shift->conflict_overridden)<span class="badge text-bg-warning">Override</span>@endif</td><td>@if($shift->status==='scheduled')<form method="POST" action="{{ route('staff.shifts.status',[$shift->staff,$shift]) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="completed"><button class="btn btn-sm btn-outline-success">Mark complete</button></form>@endif</td></tr>@endforeach
        </x-ui.data-table>{{ $shifts->links() }}
        @can('staff.schedule')<hr><h3 class="h5">Schedule shift</h3><form method="POST" action="{{ route('staff.shifts.store',$profiles->first()?->id ?? 0) }}" id="shift-form">@csrf
            <div class="row g-3"><div class="col-md-4"><x-ui.form.select name="staff_selector" label="Staff" :options="$profiles->pluck('display_name','id')" :value="$profiles->first()?->id" required/></div><div class="col-md-4"><x-ui.form.input name="title" label="Shift title" required/></div><div class="col-md-4"><x-ui.form.select name="event_id" label="Optional Event" :options="$events->mapWithKeys(fn($e)=>[$e->id=>$e->reference_number.' · '.$e->name])" placeholder="No Event"/></div><div class="col-md-4"><x-ui.form.input name="starts_at_local" label="Starts" type="datetime-local" required/></div><div class="col-md-4"><x-ui.form.input name="ends_at_local" label="Ends" type="datetime-local" required/></div><div class="col-md-4"><x-ui.form.input name="location" label="Location"/></div><div class="col-12"><x-ui.form.textarea name="notes" label="Notes" rows="2"/></div>@can('staff.override-conflicts')<div class="col-md-4"><div class="form-check"><input class="form-check-input" name="override_conflict" value="1" type="checkbox" id="shift_override"><label class="form-check-label" for="shift_override">Override detected conflict</label></div></div><div class="col-md-8"><x-ui.form.input name="override_reason" label="Override reason"/></div>@endcan</div><button class="btn btn-primary">Schedule shift</button>
        </form><script>document.getElementById('shift-form')?.addEventListener('submit',function(){const id=this.querySelector('[name="staff_selector"]').value;this.action='{{ url('/staff') }}/'+encodeURIComponent(id)+'/shifts';});</script>@endcan
    </div></section>

    <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Leave</h2>
        <x-ui.data-table :columns="[['label'=>'Staff'],['label'=>'Type'],['label'=>'Dates'],['label'=>'Status'],['label'=>'Review']]" caption="Leave requests" :empty="$leave->isEmpty()" empty-title="No leave requests">
            @foreach($leave as $request)<tr><td>{{ $request->staff->display_name }}</td><td>{{ $request->leave_type }}<span class="d-block small text-secondary">{{ str($request->reason)->limit(80) }}</span></td><td>{{ $request->starts_on->format('Y-m-d') }} – {{ $request->ends_on->format('Y-m-d') }}</td><td><x-ui.status-badge :status="$request->status"/></td><td>@can('staff.manage-leave')@if($request->status==='pending')<form method="POST" action="{{ route('staff.leave.review',$request) }}" class="d-flex gap-2">@csrf @method('PATCH')<select class="form-select form-select-sm" name="status"><option value="approved">Approve</option><option value="rejected">Reject</option></select><button class="btn btn-sm btn-outline-primary">Save</button></form>@endif @endcan</td></tr>@endforeach
        </x-ui.data-table>{{ $leave->links() }}
        @if($profiles->isNotEmpty())<hr><h3 class="h5">Request or record leave</h3><form method="POST" action="{{ route('staff.leave.store',$profiles->first()) }}" id="leave-form">@csrf<div class="row g-3"><div class="col-md-3"><x-ui.form.select name="staff_selector" label="Staff" :options="$profiles->pluck('display_name','id')" :value="$profiles->first()->id" required/></div><div class="col-md-3"><x-ui.form.input name="leave_type" label="Leave type" required/></div><div class="col-md-3"><x-ui.form.input name="starts_on" label="Starts" type="date" required/></div><div class="col-md-3"><x-ui.form.input name="ends_on" label="Ends" type="date" required/></div><div class="col-12"><x-ui.form.textarea name="reason" label="Reason" required/></div></div><button class="btn btn-primary">Submit leave request</button></form><script>document.getElementById('leave-form')?.addEventListener('submit',function(){this.action='{{ url('/staff') }}/'+encodeURIComponent(this.querySelector('[name="staff_selector"]').value)+'/leave';});</script>@endif
    </div></section>

    <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Attendance reporting inputs</h2>
        <x-ui.data-table :columns="[['label'=>'Staff'],['label'=>'Date'],['label'=>'Event'],['label'=>'Status'],['label'=>'Recorded by']]" caption="Attendance records" :empty="$attendance->isEmpty()" empty-title="No attendance records">
            @foreach($attendance as $record)<tr><td>{{ $record->staff->display_name }}</td><td>{{ $record->attendance_date->format('Y-m-d') }}</td><td>{{ $record->event?->reference_number ?? '—' }}</td><td><x-ui.status-badge :status="$record->status"/></td><td>{{ $record->recordedBy?->name ?? 'System' }}</td></tr>@endforeach
        </x-ui.data-table>{{ $attendance->links() }}
        @can('staff.record-attendance')@if($profiles->isNotEmpty())<hr><h3 class="h5">Record attendance</h3><form method="POST" action="{{ route('staff.attendance.store',$profiles->first()) }}" id="attendance-form">@csrf<div class="row g-3"><div class="col-md-3"><x-ui.form.select name="staff_selector" label="Staff" :options="$profiles->pluck('display_name','id')" :value="$profiles->first()->id" required/></div><div class="col-md-3"><x-ui.form.input name="attendance_date" label="Date" type="date" required/></div><div class="col-md-3"><x-ui.form.select name="status" label="Status" :options="collect(['present','absent','late','leave'])->mapWithKeys(fn($v)=>[$v=>str($v)->headline()])" required/></div><div class="col-md-3"><x-ui.form.select name="event_id" label="Optional Event" :options="$events->mapWithKeys(fn($e)=>[$e->id=>$e->reference_number])" placeholder="No Event"/></div><div class="col-md-6"><x-ui.form.input name="clocked_in_at" label="Clock in" type="datetime-local"/></div><div class="col-md-6"><x-ui.form.input name="clocked_out_at" label="Clock out" type="datetime-local"/></div><div class="col-12"><x-ui.form.textarea name="notes" label="Notes"/></div></div><button class="btn btn-primary">Record attendance</button></form><script>document.getElementById('attendance-form')?.addEventListener('submit',function(){this.action='{{ url('/staff') }}/'+encodeURIComponent(this.querySelector('[name="staff_selector"]').value)+'/attendance';});</script>@endif @endcan
    </div></section>

    @if($salary !== null)<section class="card border-warning mb-4"><div class="card-body p-4"><h2 class="h4">Confidential salary/payment tracking</h2><div class="alert alert-warning">Operational tracking only. This is not a statutory payroll, tax, deduction, benefits, payslip, or filing system.</div>
        <x-ui.data-table :columns="[['label'=>'Staff'],['label'=>'Period'],['label'=>'Amount'],['label'=>'Payment status'],['label'=>'Action']]" caption="Confidential salary records" :empty="$salary->isEmpty()" empty-title="No salary tracking records">@foreach($salary as $record)<tr><td>{{ $record->staff->display_name }}</td><td>{{ $record->period_starts_on->format('Y-m-d') }} – {{ $record->period_ends_on->format('Y-m-d') }}</td><td>{{ $record->currency_code }} {{ number_format((float)$record->amount,2) }}</td><td><x-ui.status-badge :status="$record->payment_status"/></td><td>@can('staff.manage-salary')@if($record->payment_status==='due')<form method="POST" action="{{ route('staff.salary.status',[$record->staff,$record]) }}" class="d-flex flex-column gap-2">@csrf @method('PATCH')<input type="hidden" name="payment_status" value="paid"><input class="form-control form-control-sm" type="date" name="paid_on" aria-label="Paid on" required><input class="form-control form-control-sm" name="payment_reference" aria-label="Payment reference" placeholder="Reference"><button class="btn btn-sm btn-outline-success">Mark paid</button></form>@endif @endcan</td></tr>@endforeach</x-ui.data-table>{{ $salary->links() }}
        @can('staff.manage-salary')@if($profiles->isNotEmpty())<hr><h3 class="h5">Add tracking record</h3><form method="POST" action="{{ route('staff.salary.store',$profiles->first()) }}" id="salary-form">@csrf<div class="row g-3"><div class="col-md-3"><x-ui.form.select name="staff_selector" label="Staff" :options="$profiles->pluck('display_name','id')" :value="$profiles->first()->id" required/></div><div class="col-md-3"><x-ui.form.input name="period_starts_on" label="Period starts" type="date" required/></div><div class="col-md-3"><x-ui.form.input name="period_ends_on" label="Period ends" type="date" required/></div><div class="col-md-3"><x-ui.form.input name="amount" label="Amount" type="number" step="0.0001" min="0" required/></div><div class="col-md-3"><x-ui.form.input name="currency_code" label="Currency" :value="$currency" required/></div><div class="col-md-3"><x-ui.form.select name="payment_status" label="Status" :options="collect(['due','paid'])->mapWithKeys(fn($v)=>[$v=>str($v)->headline()])" value="due" required/></div><div class="col-md-3"><x-ui.form.input name="paid_on" label="Paid on" type="date"/></div><div class="col-md-3"><x-ui.form.input name="payment_reference" label="Reference"/></div></div><button class="btn btn-primary">Save tracking record</button></form><script>document.getElementById('salary-form')?.addEventListener('submit',function(){this.action='{{ url('/staff') }}/'+encodeURIComponent(this.querySelector('[name="staff_selector"]').value)+'/salary-records';});</script>@endif @endcan
    </div></section>@endif

    @if($performance !== null)<section class="card"><div class="card-body p-4"><h2 class="h4">Performance records</h2><x-ui.data-table :columns="[['label'=>'Staff'],['label'=>'Event'],['label'=>'Score'],['label'=>'Summary']]" caption="Performance records" :empty="$performance->isEmpty()" empty-title="No performance records">@foreach($performance as $record)<tr><td>{{ $record->staff->display_name }}</td><td>{{ $record->event?->reference_number ?? '—' }}</td><td>{{ $record->score ?? '—' }}</td><td>{{ str($record->summary)->limit(100) }}</td></tr>@endforeach</x-ui.data-table>{{ $performance->links() }}
        @can('staff.manage-performance')@if($profiles->isNotEmpty())<hr><h3 class="h5">Record performance</h3><form method="POST" action="{{ route('staff.performance.store',$profiles->first()) }}" id="performance-form">@csrf<div class="row g-3"><div class="col-md-3"><x-ui.form.select name="staff_selector" label="Staff" :options="$profiles->pluck('display_name','id')" :value="$profiles->first()->id" required/></div><div class="col-md-3"><x-ui.form.select name="event_id" label="Optional Event" :options="$events->mapWithKeys(fn($e)=>[$e->id=>$e->reference_number])" placeholder="No Event"/></div><div class="col-md-2"><x-ui.form.input name="score" label="Score (0–100)" type="number" step="0.01" min="0" max="100"/></div><div class="col-md-2"><x-ui.form.input name="period_starts_on" label="Period starts" type="date"/></div><div class="col-md-2"><x-ui.form.input name="period_ends_on" label="Period ends" type="date"/></div><div class="col-12"><x-ui.form.textarea name="summary" label="Summary" required/></div><div class="col-md-6"><x-ui.form.textarea name="strengths" label="Strengths"/></div><div class="col-md-6"><x-ui.form.textarea name="improvement_notes" label="Improvement notes"/></div></div><button class="btn btn-primary">Save performance record</button></form><script>document.getElementById('performance-form')?.addEventListener('submit',function(){this.action='{{ url('/staff') }}/'+encodeURIComponent(this.querySelector('[name="staff_selector"]').value)+'/performance-records';});</script>@endif @endcan
    </div></section>@endif
</x-layouts.app>
