<x-layouts.app :title="'Tickets · '.$event->name" :breadcrumbs="[['label'=>'Events','url'=>route('events.index')],['label'=>$event->name,'url'=>route('events.show',$event)],['label'=>'Ticketing']]">
    <x-ui.page-header title="Ticketing" subtitle="General-admission inventory, manual issuance, Promo Codes, refunds, and one-time validation.">
        <x-slot:actions><a class="btn btn-outline-primary" href="{{ route('events.tickets.validate',$event) }}">Front-desk validation</a></x-slot:actions>
    </x-ui.page-header>
    <div class="alert alert-info">No online checkout or gateway is used. Priced Tickets must reference a posted manual Payment; free Tickets require no Payment.</div>

    @can('publish',[App\Models\Ticket::class,$event])
        <section class="card card-body mb-4"><div class="d-flex flex-wrap gap-3 justify-content-between align-items-center"><div><h2 class="h5 mb-1">Public catalogue</h2><p class="text-secondary mb-0">Public availability exists only while this Event is explicitly published. Issuance remains manager-only.</p></div><form method="POST" action="{{ route('events.tickets.publish',$event) }}">@csrf @method('PATCH')<input type="hidden" name="publish" value="{{ $event->ticketing_published_at ? 0 : 1 }}"><button class="btn {{ $event->ticketing_published_at ? 'btn-outline-warning' : 'btn-success' }}" type="submit">{{ $event->ticketing_published_at ? 'Unpublish' : 'Publish' }}</button>@if($event->ticketing_published_at)<a class="btn btn-link" target="_blank" rel="noopener" href="{{ route('public.tickets.catalogue',$event->ticketing_public_slug) }}">Open public catalogue</a>@endif</form></div></section>
    @endcan

    <section class="mb-4"><h2 class="h4">Inventory</h2><div class="row g-3">
        @forelse($types as $type)<div class="col-md-6 col-xl-4"><div class="card h-100 card-body"><div class="d-flex justify-content-between"><h3 class="h5">{{ $type->name }}</h3><x-ui.status-badge :status="$type->status"/></div><p class="small text-secondary">{{ str($type->category)->headline() }} · {{ $type->code }}</p><p class="display-6 mb-0">{{ max(0,$type->quantity_total-$type->active_tickets_count) }}</p><p class="text-secondary">of {{ $type->quantity_total }} available · {{ number_format((float)$type->price,2) }} {{ $type->currency_code }}</p>
            @can('configure',[App\Models\Ticket::class,$event])<details><summary class="btn btn-sm btn-outline-secondary">Edit</summary><form class="row g-2 mt-2" method="POST" action="{{ route('events.ticket-types.update',[$event,$type]) }}">@csrf @method('PUT')@include('events.tickets.partials.type-fields',['ticketType'=>$type])<div><button class="btn btn-sm btn-primary">Save</button></div></form><form class="mt-2" method="POST" action="{{ route('events.ticket-types.archive',[$event,$type]) }}">@csrf @method('PATCH')<label class="form-label small" for="archive_type_{{ $type->id }}">Archive reason</label><div class="input-group"><input class="form-control form-control-sm" id="archive_type_{{ $type->id }}" name="reason" required maxlength="500"><button class="btn btn-sm btn-outline-danger">Archive</button></div></form></details>@endcan
        </div></div>@empty<div class="col-12"><x-ui.empty-state title="No Ticket Types" description="Create VIP, Regular, Early Bird, or a custom general-admission category."/></div>@endforelse
    </div></section>

    @can('configure',[App\Models\Ticket::class,$event])
    <div class="row g-4 mb-4"><div class="col-lg-6"><section class="card card-body h-100"><h2 class="h5">Create Ticket Type</h2><form class="row g-2" method="POST" action="{{ route('events.ticket-types.store',$event) }}">@csrf @include('events.tickets.partials.type-fields',['ticketType'=>new App\Models\TicketType])<div><button class="btn btn-primary">Create Ticket Type</button></div></form></section></div>
    <div class="col-lg-6"><section class="card card-body h-100"><h2 class="h5">Create Promo Code</h2><p class="small text-secondary">Usage limits count Tickets issued and are not restored by cancellation or refund.</p><form class="row g-2" method="POST" action="{{ route('events.promo-codes.store',$event) }}">@csrf
        <div class="col-md-6"><label class="form-label" for="promo_code">Code</label><input class="form-control" id="promo_code" name="code" required maxlength="64"></div><div class="col-md-6"><label class="form-label" for="promo_name">Name</label><input class="form-control" id="promo_name" name="name" required></div>
        <div class="col-md-6"><label class="form-label" for="discount_type">Discount</label><select class="form-select" id="discount_type" name="discount_type"><option value="percentage">Percentage per Ticket</option><option value="fixed">Fixed amount per Ticket</option></select></div><div class="col-md-6"><label class="form-label" for="discount_value">Value</label><input class="form-control" id="discount_value" name="discount_value" type="number" step="0.0001" min="0.0001" required></div>
        <div class="col-md-4"><label class="form-label" for="valid_from">Valid from</label><input class="form-control" id="valid_from" name="valid_from" type="datetime-local"></div><div class="col-md-4"><label class="form-label" for="valid_until">Valid until</label><input class="form-control" id="valid_until" name="valid_until" type="datetime-local"></div><div class="col-md-4"><label class="form-label" for="usage_limit">Ticket-use limit</label><input class="form-control" id="usage_limit" name="usage_limit" type="number" min="1"></div><input type="hidden" name="is_active" value="1"><div><button class="btn btn-primary">Create Promo Code</button></div>
    </form></section></div></div>
    @endcan

    @if($promos->isNotEmpty())<section class="card card-body mb-4"><h2 class="h5">Promo Codes</h2><x-ui.data-table :columns="[['label'=>'Code'],['label'=>'Discount'],['label'=>'Window'],['label'=>'Limit'],['label'=>'State']]" caption="Promo Code rules" :empty="false">@foreach($promos as $promo)<tr><td><strong>{{ $promo->code }}</strong><span class="d-block small text-secondary">{{ $promo->name }}</span></td><td>{{ $promo->discount_value }} {{ $promo->discount_type==='percentage'?'%':'per Ticket' }}</td><td>{{ $promo->valid_from?->format('Y-m-d H:i') ?: 'Any' }} – {{ $promo->valid_until?->format('Y-m-d H:i') ?: 'Any' }}</td><td>{{ $promo->usage_limit ?? 'Unlimited' }}</td><td><x-ui.status-badge :status="$promo->is_active && !$promo->archived_at ? 'active':'archived'"/></td></tr>@endforeach</x-ui.data-table></section>@endif

    @can('issue',[App\Models\Ticket::class,$event])<section class="card card-body mb-4"><h2 class="h5">Issue Tickets</h2><form class="row g-3" method="POST" action="{{ route('events.ticket-orders.store',$event) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Illuminate\Support\Str::uuid() }}"><input type="hidden" name="source" value="manual">
        <div class="col-md-4"><label class="form-label" for="ticket_type_id">Ticket Type</label><select class="form-select" id="ticket_type_id" name="ticket_type_id" required><option value="">Select</option>@foreach($types->whereIn('status',['on_sale','sold_out']) as $type)<option value="{{ $type->id }}">{{ $type->name }} · {{ $type->price }} {{ $type->currency_code }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label" for="quantity">Quantity</label><input class="form-control" id="quantity" name="quantity" type="number" min="1" max="100" value="1" required></div><div class="col-md-3"><label class="form-label" for="attendee_name">Attendee</label><input class="form-control" id="attendee_name" name="attendee_name" required></div><div class="col-md-3"><label class="form-label" for="attendee_email">Email</label><input class="form-control" id="attendee_email" name="attendee_email" type="email"></div><div class="col-md-3"><label class="form-label" for="attendee_phone">Phone</label><input class="form-control" id="attendee_phone" name="attendee_phone"></div><div class="col-md-3"><label class="form-label" for="promo_code_issue">Promo Code</label><input class="form-control" id="promo_code_issue" name="promo_code"></div><div class="col-md-3"><label class="form-label" for="payment_id">Posted Payment</label><select class="form-select" id="payment_id" name="payment_id"><option value="">None / free</option>@foreach($payments as $payment)<option value="{{ $payment->id }}">{{ $payment->receipt_number }} · {{ $payment->amount }} {{ $payment->currency_code }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label" for="registration_id">Approved Registration</label><select class="form-select" id="registration_id" name="registration_id"><option value="">None</option>@foreach($registrations as $registration)<option value="{{ $registration->id }}">{{ $registration->reference_number }} · {{ $registration->registrant_name }}</option>@endforeach</select></div><div class="col-12"><label class="form-label" for="order_notes">Notes</label><textarea class="form-control" id="order_notes" name="notes" rows="2"></textarea></div><div><button class="btn btn-primary">Issue Ticket Order</button></div>
    </form></section>@endcan

    <section><h2 class="h4">Orders and attendee lookup</h2><x-ui.filter-bar method="GET" :action="route('events.tickets.index',$event)"><div class="col-md-5"><label class="form-label" for="q">Search</label><input class="form-control" id="q" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Order, attendee, email, Ticket number"></div><div class="col-md-3"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">All</option>@foreach(App\Models\TicketOrder::STATUSES as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ str($status)->headline() }}</option>@endforeach</select></div></x-ui.filter-bar>
        <x-ui.data-table :columns="[['label'=>'Order'],['label'=>'Attendee'],['label'=>'Type / Qty'],['label'=>'Total'],['label'=>'Status'],['label'=>'Issued']]" caption="Ticket Orders" :empty="$orders->isEmpty()" empty-title="No Ticket Orders found">@foreach($orders as $order)<tr><td><a href="{{ route('events.ticket-orders.show',[$event,$order]) }}">{{ $order->reference_number }}</a></td><td>{{ $order->attendee_name }}<span class="d-block small text-secondary">{{ $order->attendee_email }}</span></td><td>{{ $order->type->name }} · {{ $order->quantity }}</td><td>{{ $order->total }} {{ $order->currency_code }}</td><td><x-ui.status-badge :status="$order->status"/></td><td>{{ $order->issued_at->format('Y-m-d H:i') }}</td></tr>@endforeach</x-ui.data-table><div class="mt-3">{{ $orders->links() }}</div>
    </section>
</x-layouts.app>
