<x-layouts.app :title="$order->reference_number" :breadcrumbs="[['label'=>'Events','url'=>route('events.index')],['label'=>$event->name,'url'=>route('events.show',$event)],['label'=>'Ticketing','url'=>route('events.tickets.index',$event)],['label'=>$order->reference_number]]">
    <x-ui.page-header :title="$order->reference_number" :subtitle="$order->attendee_name.' · '.$order->type->name"><x-slot:actions><a class="btn btn-outline-primary" href="{{ route('events.ticket-orders.print',[$event,$order]) }}" target="_blank">Print</a><x-ui.status-badge :status="$order->status"/></x-slot:actions></x-ui.page-header>
    <div class="row g-4"><div class="col-lg-8"><section class="card card-body mb-4"><h2 class="h5">Issued Tickets</h2><div class="row g-3">@foreach($order->tickets as $ticket)<div class="col-md-6"><article class="border rounded p-3 h-100"><div class="d-flex justify-content-between"><strong>{{ $ticket->ticket_number }}</strong><x-ui.status-badge :status="$ticket->status"/></div><img class="img-fluid d-block mx-auto my-3" width="220" height="220" alt="QR for {{ $ticket->ticket_number }}" src="{{ route('events.tickets.qr',[$event,$ticket]) }}"><p class="mb-1">{{ $ticket->final_price_snapshot }} {{ $ticket->currency_code }}</p>@if($ticket->validation)<p class="small text-secondary">Used {{ $ticket->validation->validated_at->format('Y-m-d H:i') }} by {{ $ticket->validation->validatedBy?->name ?? 'former user' }}</p>@endif
                    @if($ticket->status==='issued')@can('refund',$ticket)<details><summary class="btn btn-sm btn-outline-danger">Refund</summary><form class="mt-2" method="POST" action="{{ route('events.tickets.refunds.store',[$event,$ticket]) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Illuminate\Support\Str::uuid() }}"><input type="hidden" name="refunded_at" value="{{ now()->format('Y-m-d H:i:s') }}"><label class="form-label" for="refund_reason_{{ $ticket->id }}">Reason</label><input class="form-control mb-2" id="refund_reason_{{ $ticket->id }}" name="reason" required maxlength="500"><button class="btn btn-danger btn-sm">Record refund</button></form></details>@endcan @endif
                </article></div>@endforeach</div></section></div>
        <aside class="col-lg-4"><section class="card card-body mb-4"><h2 class="h5">Order summary</h2><dl class="row mb-0"><dt class="col-6">Quantity</dt><dd class="col-6">{{ $order->quantity }}</dd><dt class="col-6">Subtotal</dt><dd class="col-6">{{ $order->subtotal }}</dd><dt class="col-6">Discount</dt><dd class="col-6">{{ $order->discount_total }}</dd><dt class="col-6">Total</dt><dd class="col-6"><strong>{{ $order->total }} {{ $order->currency_code }}</strong></dd><dt class="col-6">Payment</dt><dd class="col-6">{{ $order->payment?->receipt_number ?? ($order->total==='0.0000'?'Free':'—') }}</dd></dl></section>
        @can('email',$order->tickets->first())<section class="card card-body mb-4"><h2 class="h5">Email Tickets</h2><p class="small text-secondary">Synchronous delivery is logged. The Event catalogue must be published.</p><form method="POST" action="{{ route('events.ticket-orders.email',[$event,$order]) }}">@csrf<label class="form-label" for="recipient_address">Email</label><input class="form-control mb-2" id="recipient_address" name="recipient_address" type="email" required value="{{ $order->attendee_email }}"><button class="btn btn-outline-primary">Send</button></form></section>@endcan
        @can('issue',[App\Models\Ticket::class,$event])@if($order->status!=='cancelled')<section class="card card-body"><h2 class="h5">Cancel order</h2><p class="small text-secondary">Paid active Tickets must be refunded first. Used Tickets cannot be cancelled.</p><form method="POST" action="{{ route('events.ticket-orders.cancel',[$event,$order]) }}">@csrf @method('PATCH')<label class="form-label" for="cancel_reason">Reason</label><input class="form-control mb-2" id="cancel_reason" name="reason" required maxlength="500"><button class="btn btn-outline-danger">Cancel order</button></form></section>@endif @endcan</aside></div>
</x-layouts.app>
