<?php

return [
    'permissions' => [
        'dashboard.view' => 'View the dashboard',
        'users.view' => 'View users',
        'users.create' => 'Create users',
        'users.update' => 'Update users',
        'users.delete' => 'Archive users',
        'users.assign' => 'Assign user roles',
        'events.view' => 'View events',
        'events.create' => 'Create events',
        'events.update' => 'Update events',
        'events.delete' => 'Archive events',
        'events.approve' => 'Approve events and workflow transitions',
        'events.export' => 'Export event data',
        'events.assign' => 'Assign event work',
        'events.correct' => 'Reopen completed events for privileged correction',
        'bookings.view' => 'View booking enquiries',
        'bookings.create' => 'Create booking enquiries',
        'bookings.update' => 'Review booking enquiries',
        'bookings.approve' => 'Approve and confirm bookings',
        'bookings.cancel' => 'Cancel bookings',
        'bookings.reschedule' => 'Reschedule bookings',
        'bookings.waitlist' => 'Manage the booking waitlist',
        'bookings.convert' => 'Convert confirmed bookings to events',
        'bookings.override-conflicts' => 'Override known booking resource conflicts',
        'venues.view' => 'View venues and availability',
        'venues.create' => 'Create venues',
        'venues.update' => 'Update venues and venue configuration',
        'venues.delete' => 'Archive and reactivate venues',
        'venues.allocate' => 'Allocate venues to events',
        'venues.override-conflicts' => 'Override exclusive venue allocation conflicts',
        'event-templates.view' => 'View event templates and the module registry',
        'event-templates.configure' => 'Configure event templates and module display settings',
        'payments.view' => 'View payments',
        'payments.create' => 'Record payments',
        'payments.refund' => 'Record refunds',
        'payments.export' => 'Export payment data',
        'invoices.view' => 'View Invoices and balances',
        'invoices.create' => 'Create Invoice drafts and line items',
        'invoices.update' => 'Update Invoice drafts',
        'invoices.issue' => 'Issue immutable Invoices',
        'invoices.cancel' => 'Cancel unpaid Invoices',
        'invoices.credit' => 'Create traceable Invoice credits',
        'invoices.email' => 'Email issued Invoices synchronously',
        'invoices.export' => 'Download and print Invoice PDFs',
        'settings.view' => 'View settings',
        'settings.configure' => 'Configure settings',
        'branches.view' => 'View branches',
        'branches.configure' => 'Configure branches',
        'master-data.view' => 'View configurable master data',
        'master-data.configure' => 'Configure master data',
        'audit.view' => 'View audit history',
        'clients.view' => 'View clients',
        'clients.create' => 'Create clients',
        'clients.update' => 'Update clients and contacts',
        'clients.delete' => 'Archive and reactivate clients',
        'clients.assign' => 'Link client portal users',
        'clients.merge' => 'Merge duplicate clients',
        'vendors.view' => 'View vendors',
        'vendors.view-own' => 'View a linked vendor profile',
        'vendors.create' => 'Create vendors',
        'vendors.update' => 'Update vendors, contacts, and service areas',
        'vendors.delete' => 'Archive and reactivate vendors',
        'vendors.assign' => 'Link vendor portal users',
        'vendors.view-work' => 'View event vendor assignments and work orders',
        'vendors.update-work' => 'Update assigned vendor delivery and work-order status',
        'vendors.approve-cost' => 'Approve vendor assignment costs and invoice metadata',
        'vendors.manage-availability' => 'Manage vendor availability rules',
        'vendors.rate' => 'Rate completed vendor assignments',
        'vendors.upload-invoice' => 'Upload vendor invoices to protected storage',
        'staff.view' => 'View staff profiles',
        'staff.view-own' => 'View a linked staff profile',
        'staff.create' => 'Create staff profiles',
        'staff.update' => 'Update staff profiles',
        'staff.delete' => 'Archive and reactivate staff profiles',
        'staff.assign' => 'Link staff portal users',
        'staff.view-work' => 'View staff schedules, assignments, leave, attendance, and performance',
        'staff.view-own-work' => 'View a linked staff profile schedule and assignments',
        'staff.schedule' => 'Create and update staff shifts and event assignments',
        'staff.update-own-work' => 'Update status for own shifts and assignments',
        'staff.request-leave' => 'Request leave for the linked staff profile',
        'staff.manage-leave' => 'Review and manage staff leave',
        'staff.record-attendance' => 'Record staff attendance',
        'staff.view-salary' => 'View confidential salary/payment tracking records',
        'staff.manage-salary' => 'Create confidential salary/payment tracking records',
        'staff.manage-performance' => 'Create staff performance records',
        'staff.override-conflicts' => 'Override staff scheduling conflicts with a reason',
        'tasks.view' => 'View Event tasks',
        'tasks.view-assigned' => 'View assigned Event tasks',
        'tasks.create' => 'Create Event tasks',
        'tasks.update' => 'Update Event tasks',
        'tasks.assign' => 'Assign Event tasks',
        'tasks.comment' => 'Comment on Event tasks',
        'tasks.complete' => 'Update progress and complete Event tasks',
        'tasks.attach' => 'Attach protected files to Event tasks',
        'tasks.delete' => 'Archive Event tasks',
        'guests.view' => 'View Event Guests, RSVP, groups, seating, and check-in state',
        'guests.create' => 'Create Event Guests and groups',
        'guests.update' => 'Update Event Guests and group membership',
        'guests.delete' => 'Archive and reactivate Event Guests',
        'guests.invite' => 'Issue and revoke Guest invitations',
        'guests.manage-rsvp' => 'Record and update Guest RSVP responses',
        'guests.manage-seating' => 'Assign Guest tables and seats',
        'guests.add-notes' => 'Add operational or private Guest notes',
        'guests.view-private-notes' => 'View private Guest notes',
        'guests.check-in' => 'Look up and check in Guests',
        'registrations.view' => 'View Registration forms and submissions',
        'registrations.create' => 'Enter offline Registrations',
        'registrations.configure' => 'Configure and publish Registration forms',
        'registrations.approve' => 'Approve or reject Registration submissions',
        'registrations.export' => 'Export Registration responses',
        'registrations.convert-guest' => 'Convert approved Registrations to Guests',
        'tickets.view' => 'View Ticket Types, orders, inventory, and validation state',
        'tickets.configure' => 'Configure Ticket Types and Promo Codes',
        'tickets.issue' => 'Issue and cancel manual or free Ticket Orders',
        'tickets.refund' => 'Refund Tickets through traceable manual finance records',
        'tickets.validate' => 'Validate Ticket QR tokens at the front desk',
        'tickets.email' => 'Email issued Ticket links synchronously',
        'tickets.publish' => 'Publish and unpublish the public Ticket catalogue',
        'calendar.view' => 'View the consolidated calendar',
        'budget.view' => 'View Event budgets and summaries',
        'budget.manage' => 'Create and manage Event budget lines',
        'budget.approve' => 'Approve and lock Event budget baselines',
        'finance.view' => 'View Event income, expenses, and recognized profit',
        'finance.create' => 'Create and edit draft income and expense entries',
        'finance.approve' => 'Approve and post income and expense entries',
        'finance.void' => 'Void drafts or reverse posted financial entries',
        'documents.view' => 'View authorized documents',
        'documents.create' => 'Upload documents',
        'documents.update' => 'Replace document versions',
        'documents.delete' => 'Archive documents',
        'documents.download' => 'Download authorized documents',
        'notifications.view' => 'View and manage own notification inbox',
        'communications.view' => 'View Event communication history',
        'communications.send' => 'Send synchronous Event communications',
        'communications.retry' => 'Retry failed Event communications',
        'communications.configure' => 'Configure communication templates and reminders',
    ],

    'roles' => [
        'administrator' => [
            'name' => 'Administrator / Business Manager',
            'permissions' => ['*'],
        ],
        'event-manager' => [
            'name' => 'Event Manager',
            'permissions' => [
                'dashboard.view', 'events.view', 'events.create', 'events.update',
                'events.delete', 'events.approve', 'events.export', 'events.assign',
                'bookings.view', 'bookings.create', 'bookings.update', 'bookings.approve',
                'bookings.cancel', 'bookings.reschedule', 'bookings.waitlist', 'bookings.convert',
                'event-templates.view',
                'venues.view', 'venues.create', 'venues.update', 'venues.delete', 'venues.allocate',
                'documents.view', 'documents.create', 'documents.update', 'documents.download',
                'clients.view', 'clients.create', 'clients.update',
                'vendors.view', 'vendors.create', 'vendors.update',
                'vendors.view-work', 'vendors.assign', 'vendors.approve-cost',
                'vendors.manage-availability', 'vendors.rate', 'vendors.upload-invoice',
                'staff.view', 'staff.create', 'staff.update', 'staff.view-work',
                'staff.schedule', 'staff.manage-leave', 'staff.record-attendance',
                'staff.manage-performance',
                'tasks.view', 'tasks.create', 'tasks.update', 'tasks.assign', 'tasks.comment',
                'tasks.complete', 'tasks.attach', 'tasks.delete', 'calendar.view',
                'guests.view', 'guests.create', 'guests.update', 'guests.delete',
                'guests.invite', 'guests.manage-rsvp', 'guests.manage-seating',
                'guests.add-notes', 'guests.view-private-notes', 'guests.check-in',
                'registrations.view', 'registrations.create', 'registrations.configure',
                'registrations.approve', 'registrations.export', 'registrations.convert-guest',
                'tickets.view', 'tickets.configure', 'tickets.issue', 'tickets.validate',
                'tickets.email', 'tickets.publish',
                'budget.view', 'budget.manage', 'budget.approve', 'finance.view', 'finance.create',
                'invoices.view', 'invoices.create', 'invoices.update', 'invoices.issue', 'invoices.email', 'invoices.export',
                'notifications.view', 'communications.view', 'communications.send',
                'communications.retry', 'communications.configure',
            ],
        ],
        'staff' => [
            'name' => 'Staff',
            'permissions' => [
                'dashboard.view', 'events.view', 'venues.view', 'staff.view-own',
                'staff.view-own-work', 'staff.update-own-work', 'staff.request-leave',
                'documents.view', 'documents.download',
                'tasks.view-assigned', 'tasks.comment', 'tasks.complete', 'tasks.attach', 'calendar.view',
                'guests.view',
                'notifications.view',
            ],
        ],
        'client' => [
            'name' => 'Client',
            'permissions' => ['dashboard.view', 'notifications.view'],
        ],
        'vendor' => [
            'name' => 'Vendor',
            'permissions' => [
                'dashboard.view', 'vendors.view-own', 'vendors.view-work', 'vendors.update-work',
                'vendors.manage-availability', 'vendors.upload-invoice',
                'documents.view', 'documents.create', 'documents.download',
                'calendar.view',
                'notifications.view', 'communications.view',
            ],
        ],
        'finance-accounts' => [
            'name' => 'Finance / Accounts',
            'permissions' => [
                'dashboard.view', 'events.view', 'payments.view', 'payments.create',
                'payments.refund', 'payments.export', 'vendors.view-work', 'vendors.approve-cost',
                'staff.view', 'staff.view-work', 'staff.view-salary', 'staff.manage-salary',
                'calendar.view', 'budget.view', 'budget.manage', 'budget.approve',
                'finance.view', 'finance.create', 'finance.approve', 'finance.void',
                'invoices.view', 'invoices.create', 'invoices.update', 'invoices.issue',
                'invoices.cancel', 'invoices.credit', 'invoices.email', 'invoices.export',
                'tickets.view', 'tickets.refund',
                'notifications.view', 'communications.view', 'communications.send', 'communications.retry',
            ],
        ],
        'front-desk-check-in' => [
            'name' => 'Front Desk / Check-in',
            'permissions' => ['dashboard.view', 'events.view', 'guests.view', 'guests.check-in', 'tickets.view', 'tickets.validate', 'notifications.view'],
        ],
    ],

    'development_administrator' => [
        'name' => env('DEV_ADMIN_NAME'),
        'email' => env('DEV_ADMIN_EMAIL'),
        'password' => env('DEV_ADMIN_PASSWORD'),
    ],
];
