<x-layouts.app :title="'Guest check-in · '.$event->name" :breadcrumbs="[['label'=>'Events','url'=>route('events.index')],['label'=>$event->name,'url'=>route('events.show',$event)],['label'=>'Guests','url'=>route('events.guests.index',$event)],['label'=>'Check-in']]">
    <x-ui.page-header title="Front-desk guest check-in" :subtitle="$event->reference_number.' · '.$event->name"/>
    <section class="card mb-4"><div class="card-body p-4"><form method="GET" action="{{ route('events.guests.check-in.lookup',$event) }}"><div class="row align-items-end"><div class="col-md-9"><x-ui.form.input name="token" label="Scan or paste check-in token" :value="request('token')" required autocomplete="off"/></div><div class="col-md-3"><button class="btn btn-primary w-100 mb-3">Look up</button></div></div></form></div></section>
    @if($error)<div class="alert alert-danger" role="alert">{{ $error }}</div>@endif
    @if($result)<section class="card"><div class="card-body p-4">
        @if($result->alreadyCheckedIn)<div class="alert alert-warning" role="status"><strong>Already Checked In.</strong> Original check-in: {{ $result->checkIn->checked_in_at->format('Y-m-d H:i:s') }} by {{ $result->checkIn->operator?->name ?? 'System' }}. No duplicate attendance was created.</div>@endif
        <h2 class="h3">{{ $result->invitation->guest->display_name }}</h2><dl class="row"><dt class="col-sm-4">RSVP</dt><dd class="col-sm-8">{{ str($result->invitation->guest->rsvp_status)->headline() }} · {{ $result->invitation->guest->confirmed_party_size ?: $result->invitation->guest->invited_party_size }} expected</dd><dt class="col-sm-4">VIP</dt><dd class="col-sm-8">{{ $result->invitation->guest->is_vip?'Yes':'No' }}</dd><dt class="col-sm-4">Group</dt><dd class="col-sm-8">{{ $result->invitation->guest->groupMembership?->group?->name ?? '—' }}</dd><dt class="col-sm-4">Seat</dt><dd class="col-sm-8">{{ $result->invitation->guest->seatAssignment ? $result->invitation->guest->seatAssignment->table_label.' / '.$result->invitation->guest->seatAssignment->seat_label : '—' }}</dd></dl>
        @unless($result->alreadyCheckedIn)<form method="POST" action="{{ route('events.guests.check-in.store',$event) }}">@csrf<input type="hidden" name="token" value="{{ request('token') }}"><x-ui.form.input name="party_size" label="Party checking in" type="number" min="1" :max="max(1,$result->invitation->guest->confirmed_party_size ?: $result->invitation->guest->invited_party_size)" :value="max(1,$result->invitation->guest->confirmed_party_size ?: $result->invitation->guest->invited_party_size)" required/><x-ui.form.textarea name="notes" label="Check-in note" rows="2"/><button class="btn btn-success btn-lg">Check in once</button></form>@endunless
    </div></section>@endif
</x-layouts.app>
