<x-layouts.app :title="$guest->display_name" wide :breadcrumbs="[['label'=>'Events','url'=>route('events.index')],['label'=>$event->name,'url'=>route('events.show',$event)],['label'=>'Guests','url'=>route('events.guests.index',$event)],['label'=>$guest->display_name]]">
    <x-ui.page-header :title="$guest->display_name" :subtitle="$event->reference_number.' · Guest record without login'">
        <x-slot:actions>@if($guest->is_vip)<span class="badge text-bg-warning fs-6">VIP</span>@endif @can('update',$guest)<a class="btn btn-outline-primary" href="{{ route('events.guests.edit',[$event,$guest]) }}">Edit guest</a>@endcan</x-slot:actions>
    </x-ui.page-header>

    @if($guest->archived_at)<div class="alert alert-warning" role="status">This Guest is archived. Invitations were revoked and history remains available.</div>@endif
    @if($capacity['warning'])<div class="alert alert-warning" role="status">Confirmed Guest attendance exceeds the selected venue capacity.</div>@endif

    <div class="row g-4"><div class="col-xl-8">
        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Guest summary</h2><dl class="row mb-0">
            <dt class="col-sm-4">Contact</dt><dd class="col-sm-8">{{ $guest->email ?: '—' }} @if($guest->phone)<span class="d-block">{{ $guest->phone }}</span>@endif</dd>
            <dt class="col-sm-4">Group/family</dt><dd class="col-sm-8">{{ $guest->groupMembership?->group?->name ?? '—' }} @if($guest->groupMembership?->relationship_label)<span class="text-secondary">({{ $guest->groupMembership->relationship_label }})</span>@endif</dd>
            <dt class="col-sm-4">Party policy</dt><dd class="col-sm-8">{{ str($guest->plus_one_policy)->headline() }} · limit {{ $guest->plus_one_limit }} · invited party {{ $guest->invited_party_size }}</dd>
            <dt class="col-sm-4">RSVP</dt><dd class="col-sm-8"><x-ui.status-badge :status="$guest->rsvp_status"/> @if($guest->confirmed_party_size){{ $guest->confirmed_party_size }} attending @endif</dd>
            <dt class="col-sm-4">Seating</dt><dd class="col-sm-8">{{ $guest->seatAssignment ? $guest->seatAssignment->table_label.' / '.$guest->seatAssignment->seat_label : 'Not assigned' }}</dd>
            <dt class="col-sm-4">Check-in</dt><dd class="col-sm-8">@if($guest->checkIn)Checked in {{ $guest->checkIn->checked_in_at->format('Y-m-d H:i') }} by {{ $guest->checkIn->operator?->name ?? 'System' }}@else Not checked in @endif</dd>
        </dl></div></section>

        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Invitation and QR</h2>
            @forelse($guest->invitations as $invitation)<article class="border rounded p-3 mb-3"><div class="d-flex flex-wrap justify-content-between gap-3"><span><x-ui.status-badge :status="$invitation->status"/> {{ str($invitation->delivery_channel)->headline() }} · {{ $invitation->issued_at->format('Y-m-d H:i') }}</span>@if($invitation->isUsable() && auth()->user()->can('viewInvitation',$guest))<a class="btn btn-sm btn-outline-primary" target="_blank" rel="noopener" href="{{ route('events.guests.invitations.qr',[$event,$guest,$invitation]) }}">Open QR SVG</a>@endif</div>@if($invitation->expires_at)<p class="small text-secondary mb-0 mt-2">Expires {{ $invitation->expires_at->format('Y-m-d H:i') }}</p>@endif
                @if($invitation->isUsable() && auth()->user()->can('invite',$guest))<form class="mt-3" method="POST" action="{{ route('events.guests.invitations.revoke',[$event,$guest,$invitation]) }}">@csrf @method('PATCH')<div class="row align-items-end"><div class="col-md-9"><x-ui.form.input name="reason" label="Revocation reason" required/></div><div class="col-md-3"><button class="btn btn-outline-danger mb-3 w-100">Revoke</button></div></div></form>@endif
            </article>@empty<p class="text-secondary">No invitation issued.</p>@endforelse
            @can('invite',$guest)<form method="POST" action="{{ route('events.guests.invitations.store',[$event,$guest]) }}">@csrf<div class="row"><div class="col-md-5"><x-ui.form.select name="delivery_channel" label="Delivery channel" :options="collect(['manual'=>'Manual','print'=>'Print','email'=>'Email','sms'=>'SMS','whatsapp'=>'WhatsApp'])" value="manual" required/></div><div class="col-md-5"><x-ui.form.input name="expires_at" label="Optional expiry" type="datetime-local"/></div><div class="col-md-2"><div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="mark_sent" value="1" id="mark_sent"><label class="form-check-label" for="mark_sent">Mark sent</label></div></div></div><p class="small text-secondary">Issuing a replacement revokes the earlier token. SMS/WhatsApp selection records intended delivery only; no provider send occurs here.</p><button class="btn btn-primary">Issue invitation</button></form>@endcan
        </div></section>

        <section class="card"><div class="card-body p-4"><h2 class="h4">Guest notes</h2>
            @forelse($guest->notes as $note)<article class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><span class="badge {{ $note->visibility==='private'?'text-bg-danger':'text-bg-info' }}">{{ str($note->visibility)->headline() }}</span><small class="text-secondary">{{ $note->author?->name ?? 'System' }} · {{ $note->created_at->format('Y-m-d H:i') }}</small></div><p class="mb-0 mt-2">{{ $note->body }}</p></article>@empty<p class="text-secondary">No visible notes.</p>@endforelse
            @can('addNote',$guest)<form method="POST" action="{{ route('events.guests.notes.store',[$event,$guest]) }}">@csrf<x-ui.form.select name="visibility" label="Visibility" :options="collect(['operations'=>'Operations staff','private'=>'Private managers'])" value="private" required/><x-ui.form.textarea name="body" label="Note" rows="3" required/><button class="btn btn-outline-primary">Add note</button></form>@endcan
        </div></section>
    </div><aside class="col-xl-4">
        @can('manageRsvp',$guest)<section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Record RSVP</h2><form method="POST" action="{{ route('events.guests.rsvp',[$event,$guest]) }}">@csrf @method('PUT')<x-ui.form.select name="status" label="Status" :options="collect(['pending'=>'Pending','accepted'=>'Accepted','declined'=>'Declined','tentative'=>'Tentative'])" :value="$guest->rsvp_status" required/><x-ui.form.input name="attending_count" label="Attending count" type="number" min="0" max="100" :value="$guest->rsvp?->attending_count ?? 0" required/><x-ui.form.input name="plus_one_count" label="Plus-one count" type="number" min="0" :max="$guest->plus_one_limit" :value="$guest->rsvp?->plus_one_count ?? 0"/><x-ui.form.select name="response_source" label="Response source" :options="collect(['manager'=>'Manager','guest'=>'Guest','phone'=>'Phone','email'=>'Email','import'=>'Import'])" :value="$guest->rsvp?->response_source ?? 'manager'" required/><x-ui.form.textarea name="response_note" label="Response note" rows="2"/><button class="btn btn-primary">Save RSVP</button></form></div></section>@endcan

        @can('manageSeating',$guest)<section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Seating</h2><form method="POST" action="{{ route('events.guests.seat',[$event,$guest]) }}">@csrf @method('PUT')<x-ui.form.select name="guest_group_id" label="Group context" :options="$groups->pluck('name','id')" :value="$guest->seatAssignment?->guest_group_id ?? $guest->groupMembership?->guest_group_id" placeholder="No group"/><x-ui.form.input name="table_label" label="Table label" :value="$guest->seatAssignment?->table_label" required/><x-ui.form.input name="seat_label" label="Seat label" :value="$guest->seatAssignment?->seat_label" required/><x-ui.form.textarea name="notes" label="Seating note" :value="$guest->seatAssignment?->notes" rows="2"/><button class="btn btn-outline-primary">Save seat</button></form></div></section>@endcan

        @can('archive',$guest)<section class="card"><div class="card-body p-4"><h2 class="h4">{{ $guest->archived_at?'Reactivate':'Archive' }} guest</h2><form method="POST" action="{{ route('events.guests.status',[$event,$guest]) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="{{ $guest->archived_at?'reactivate':'archive' }}"><x-ui.form.textarea name="reason" label="Reason" rows="2" :required="!$guest->archived_at"/><button class="btn {{ $guest->archived_at?'btn-success':'btn-warning' }}">{{ $guest->archived_at?'Reactivate':'Archive' }}</button></form></div></section>@endcan
    </aside></div>
</x-layouts.app>
