<x-layouts.app title="Venues" wide :breadcrumbs="[['label'=>'Overview','url'=>route('home')],['label'=>'Venues']]">
    <x-ui.page-header title="Venues" subtitle="Owned and third-party places, rooms, capacity, pricing guidance, and availability."><x-slot:actions><a class="btn btn-outline-primary" href="{{ route('venues.availability') }}">Availability</a>@can('create',App\Models\Venue::class)<a class="btn btn-primary" href="{{ route('venues.create') }}">Create venue</a>@endcan</x-slot:actions></x-ui.page-header>
    <x-ui.filter-bar :action="route('venues.index')" :clear-url="route('venues.index')">
        <div class="col-12 col-lg-4"><label class="form-label" for="q">Search</label><input class="form-control" id="q" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Name, city, or address"></div>
        <div class="col-6 col-lg-2"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">Active</option><option value="archived" @selected(($filters['status']??'')==='archived')>Archived</option></select></div>
        <div class="col-6 col-lg-2"><label class="form-label" for="type">Type</label><select class="form-select" id="type" name="type"><option value="">All</option><option value="owned" @selected(($filters['type']??'')==='owned')>Owned</option><option value="third_party" @selected(($filters['type']??'')==='third_party')>Third party</option></select></div>
        @if($branches->isNotEmpty())<div class="col-6 col-lg-3"><label class="form-label" for="branch">Branch</label><select class="form-select" id="branch" name="branch"><option value="">All branches</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string)($filters['branch']??'')===(string)$branch->id)>{{ $branch->name }}</option>@endforeach</select></div>@endif
    </x-ui.filter-bar>
    <x-ui.data-table :columns="[['label'=>'Venue'],['label'=>'Type'],['label'=>'Capacity'],['label'=>'Location'],['label'=>'Status'],['label'=>'Action']]" caption="Venue records" :empty="$venues->isEmpty()" empty-title="No venues match these filters">
        @foreach($venues as $venue)<tr><td><a class="fw-semibold text-decoration-none" href="{{ route('venues.show',$venue) }}">{{ $venue->name }}</a><span class="d-block small text-secondary">{{ $venue->branch?->name ?? 'Unscoped' }}</span></td><td>{{ str($venue->type)->replace('_',' ')->headline() }}</td><td>{{ $venue->capacity ? number_format($venue->capacity) : 'Quoted / not set' }}</td><td>{{ collect([$venue->city,$venue->country_code])->filter()->join(', ') ?: '—' }}</td><td><x-ui.status-badge :status="$venue->status"/></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('venues.show',$venue) }}">View</a></td></tr>@endforeach
    </x-ui.data-table><x-ui.pagination :paginator="$venues"/>
</x-layouts.app>
