<x-layouts.app :title="$venue->name" wide :breadcrumbs="[['label'=>'Venues','url'=>route('venues.index')],['label'=>$venue->name]]">
    <x-ui.page-header :title="$venue->name" :subtitle="str($venue->type)->replace('_',' ')->headline().' · '.str($venue->status)->headline()">
        <x-slot:actions><a class="btn btn-outline-primary" href="{{ route('venues.availability',['venue'=>$venue]) }}">Availability</a>@can('update',$venue)<a class="btn btn-primary" href="{{ route('venues.edit',$venue) }}">Edit venue</a>@endcan</x-slot:actions>
    </x-ui.page-header>
    <div class="row g-4"><div class="col-xl-8">
        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Overview</h2><dl class="row mb-0">
            <dt class="col-sm-4">Capacity</dt><dd class="col-sm-8">{{ $venue->capacity ? number_format($venue->capacity) : 'Not set' }}</dd>
            <dt class="col-sm-4">Parking</dt><dd class="col-sm-8">{{ $venue->parking_capacity !== null ? number_format($venue->parking_capacity).' spaces' : 'Not set' }}</dd>
            <dt class="col-sm-4">Address</dt><dd class="col-sm-8">{{ collect([$venue->address_line_1,$venue->address_line_2,$venue->city,$venue->state_region,$venue->postal_code,$venue->country_code])->filter()->join(', ') ?: '—' }}</dd>
            <dt class="col-sm-4">Map coordinates</dt><dd class="col-sm-8">{{ $venue->latitude !== null ? $venue->latitude.', '.$venue->longitude : 'Not set' }}</dd>
            <dt class="col-sm-4">Branch</dt><dd class="col-sm-8">{{ $venue->branch?->name ?? 'Unscoped' }}</dd>
            <dt class="col-sm-4">Notes</dt><dd class="col-sm-8">{{ $venue->notes ?: '—' }}</dd>
        </dl></div></section>

        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Spaces and rooms</h2>
            <x-ui.data-table :columns="[['label'=>'Space'],['label'=>'Capacity'],['label'=>'Use'],['label'=>'Action']]" caption="Venue spaces" :empty="$venue->spaces->isEmpty()" empty-title="No spaces configured">
                @foreach($venue->spaces as $space)<tr><td>{{ $space->name }}<span class="d-block small text-secondary">{{ $space->code ?: 'No code' }}</span></td><td>{{ $space->capacity ? number_format($space->capacity) : 'Uses venue capacity' }}</td><td>{{ $space->is_exclusive ? 'Exclusive by default' : 'Shared by default' }}</td><td>@can('update',$venue)<form method="POST" action="{{ route('venues.spaces.destroy',[$venue,$space]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Archive</button></form>@endcan</td></tr>@endforeach
            </x-ui.data-table>
            @can('update',$venue)<hr><form method="POST" action="{{ route('venues.spaces.store',$venue) }}">@csrf<div class="row"><div class="col-md-5"><x-ui.form.input name="name" label="Space name" required/></div><div class="col-md-3"><x-ui.form.input name="code" label="Code"/></div><div class="col-md-4"><x-ui.form.input name="capacity" label="Capacity" type="number" min="1"/></div></div><input type="hidden" name="is_exclusive" value="0"><div class="form-check mb-3"><input class="form-check-input" type="checkbox" id="space-exclusive" name="is_exclusive" value="1" checked><label class="form-check-label" for="space-exclusive">Exclusive use by default</label></div><button class="btn btn-primary">Add space</button></form>@endcan
        </div></section>

        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Facilities</h2><ul class="list-group mb-3">@forelse($venue->facilities as $facility)<li class="list-group-item d-flex justify-content-between gap-3"><span><strong>{{ $facility->name }}</strong><span class="d-block small text-secondary">{{ $facility->space?->name ?? 'Whole venue' }}{{ $facility->details ? ' · '.$facility->details : '' }}</span></span>@can('update',$venue)<form method="POST" action="{{ route('venues.facilities.destroy',[$venue,$facility]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Archive</button></form>@endcan</li>@empty<li class="list-group-item text-secondary">No facilities recorded.</li>@endforelse</ul>
            @can('update',$venue)<form method="POST" action="{{ route('venues.facilities.store',$venue) }}">@csrf<div class="row"><div class="col-md-4"><x-ui.form.input name="name" label="Facility" required/></div><div class="col-md-4"><x-ui.form.select name="venue_space_id" label="Space" :options="$venue->spaces->pluck('name','id')" placeholder="Whole venue"/></div><div class="col-md-4"><x-ui.form.input name="details" label="Details"/></div></div><button class="btn btn-primary">Add facility</button></form>@endcan
        </div></section>

        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Pricing guidance</h2><p class="text-secondary">Rates are optional guidance. Event allocations accept a negotiated quoted price.</p><ul class="list-group mb-3">@forelse($venue->rates as $rate)<li class="list-group-item d-flex justify-content-between"><span><strong>{{ $rate->label }}</strong><span class="d-block small text-secondary">{{ $rate->amount !== null ? $rate->currency_code.' '.number_format((float)$rate->amount,2) : 'Quote required' }}{{ $rate->rate_type ? ' · '.$rate->rate_type : '' }}{{ $rate->space ? ' · '.$rate->space->name : '' }}</span></span>@can('update',$venue)<form method="POST" action="{{ route('venues.rates.destroy',[$venue,$rate]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Archive</button></form>@endcan</li>@empty<li class="list-group-item text-secondary">No rate guidance. Use quoted pricing per Event.</li>@endforelse</ul>
            @can('update',$venue)<form method="POST" action="{{ route('venues.rates.store',$venue) }}">@csrf<div class="row"><div class="col-md-4"><x-ui.form.input name="label" label="Rate label" required/></div><div class="col-md-4"><x-ui.form.input name="rate_type" label="Rate type" placeholder="Optional, e.g. day or package"/></div><div class="col-md-2"><x-ui.form.input name="amount" label="Amount" type="number" step="0.0001" min="0"/></div><div class="col-md-2"><x-ui.form.input name="currency_code" label="Currency" maxlength="3"/></div></div><button class="btn btn-primary">Add rate</button></form>@endcan
        </div></section>

        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Seating plans</h2><ul class="list-group mb-3">@forelse($venue->seatingPlans as $plan)<li class="list-group-item d-flex justify-content-between"><span>{{ $plan->name }}<span class="d-block small text-secondary">{{ $plan->space?->name ?? 'Whole venue' }} · {{ $plan->capacity ? number_format($plan->capacity).' seats' : 'capacity not set' }}</span></span>@can('update',$venue)<form method="POST" action="{{ route('venues.seating-plans.destroy',[$venue,$plan]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Archive</button></form>@endcan</li>@empty<li class="list-group-item text-secondary">No seating plan metadata.</li>@endforelse</ul>
            @can('update',$venue)<form method="POST" action="{{ route('venues.seating-plans.store',$venue) }}">@csrf<div class="row"><div class="col-md-5"><x-ui.form.input name="name" label="Plan name" required/></div><div class="col-md-4"><x-ui.form.select name="venue_space_id" label="Space" :options="$venue->spaces->pluck('name','id')" placeholder="Whole venue"/></div><div class="col-md-3"><x-ui.form.input name="capacity" label="Seats" type="number" min="1"/></div></div><x-ui.form.textarea name="layout_notes" label="Layout notes" rows="2"/><button class="btn btn-primary">Add seating plan</button></form>@endcan
        </div></section>

        <section class="card"><div class="card-body p-4"><h2 class="h4">Allocation history</h2><x-ui.data-table :columns="[['label'=>'Event'],['label'=>'Schedule'],['label'=>'Space'],['label'=>'Status']]" caption="Event venue allocations" :empty="$allocations->isEmpty()" empty-title="No Event allocations">
            @foreach($allocations as $allocation)<tr><td><a href="{{ route('events.show',$allocation->event) }}">{{ $allocation->event->reference_number }}</a></td><td>{{ $allocation->event->starts_at->format('M j, Y H:i') }} – {{ $allocation->event->ends_at->format('M j, Y H:i') }}</td><td>{{ $allocation->space?->name ?? 'Whole venue' }}</td><td><x-ui.status-badge :status="$allocation->status"/></td></tr>@endforeach
        </x-ui.data-table><x-ui.pagination :paginator="$allocations"/></div></section>
    </div><aside class="col-xl-4">
        <section class="card mb-4"><div class="card-body p-4"><h2 class="h4">Protected images</h2>@forelse($venue->media as $media)<div class="border rounded p-2 mb-2"><a href="{{ route('documents.download',$media->document) }}">{{ $media->caption ?: $media->document->title }}</a><span class="d-block small text-secondary">{{ $media->alt_text }}</span></div>@empty<p class="text-secondary">No images uploaded.</p>@endforelse
            @can('update',$venue)@if(auth()->user()->hasPermission('documents.create'))<form method="POST" action="{{ route('venues.media.store',$venue) }}" enctype="multipart/form-data">@csrf<x-ui.form.input name="file" label="Image" type="file" accept=".jpg,.jpeg,.png,.webp" required/><x-ui.form.input name="caption" label="Caption"/><x-ui.form.input name="alt_text" label="Alternative text" required/><input type="hidden" name="is_primary" value="0"><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_primary" value="1" id="primary-image"><label class="form-check-label" for="primary-image">Primary image</label></div><button class="btn btn-primary">Upload privately</button></form>@endif @endcan
        </div></section>
        @if($venue->status==='active')@can('archive',$venue)<section class="card"><div class="card-body p-4"><h2 class="h4">Archive venue</h2><p class="text-secondary">Historical allocations and documents remain available.</p><form method="POST" action="{{ route('venues.status',$venue) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="archive"><x-ui.form.textarea name="reason" label="Reason" required/><button class="btn btn-warning">Archive venue</button></form></div></section>@endcan @else @can('reactivate',$venue)<form method="POST" action="{{ route('venues.status',$venue) }}">@csrf @method('PATCH')<input type="hidden" name="action" value="reactivate"><button class="btn btn-success">Reactivate venue</button></form>@endcan @endif
    </aside></div>
</x-layouts.app>
